### ISSUE TITLE
Failed to activate the html-significant-other package

### ISSUE THREAD

**Issue by rickydazla** [javakat/html-significant-other#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [html-significant-other](https://github.com/javakat/html-significant-other) package, v0.4.2
### Stack Trace

Failed to activate the html-significant-other package

```
At undefined is not a function

TypeError: undefined is not a function
  at /Users/Rick/.atom/packages/html-significant-other/lib/html-significant-other.js:16:18
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:284:9)
  at Object.module.exports.activate (/Users/Rick/.atom/packages/html-significant-other/lib/html-significant-other.js:12:43)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -1:02.3 command-palette:toggle (atom-text-editor.editor)
  5x -0:59.9 core:move-down (atom-text-editor.editor.mini)
     -0:58.1 core:confirm (atom-text-editor.editor.mini)
     -0:58.1 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:40.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term2",
      "autocomplete-plus"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.8
file-icons, v1.5.1
git-log, v0.3.0
git-tab-status, v1.5.3
html-significant-other, v0.4.2
language-liquid, v0.2.0
linter, v0.12.0
linter-csslint, v0.0.11
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by jakeharris** [comment]
I'll be working on this this weekend. Thanks for letting me know!

**Comment by jakeharris** [comment]
Any chance you can take a look and see if that fixed it @rickydazla? The problem is that you don't have Atom's `bracket-matcher` package installed in your `~/.atom` directory, so I have to force that to install somehow. This is complicated by the fact that Atom's bracket-matcher doesn't exist on npm because [there already exists a project with that name](https://www.npmjs.com/package/bracket-matcher), so [the Atom team has only hosted it via apm](https://atom.io/packages/bracket-matcher). 

The only real question, if I understand what's going on here, is whether what I've done in using @travs's [atom-package-dependencies](https://github.com/travs/atom-package-dependencies) will actually be run (and `bracket-matcher` installed and prepared) in time for `significant-other` to succeed.

**Comment by rickydazla** [comment]
hmm I'm actually now getting [this issue](https://github.com/javakat/html-significant-other/issues/7)

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [html-significant-other](https://github.com/javakat/html-significant-other) package, v0.4.2

### Stack Trace

Failed to load the html-significant-other package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/Rick/.atom/packages/html-significant-other/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/Rick/.atom/packages/html-significant-other/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term2",
      "autocomplete-plus",
      "git-tab-status"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.8
file-icons, v1.5.1
git-log, v0.3.0
html-significant-other, v0.4.2
language-liquid, v0.2.0
linter, v0.12.0
linter-csslint, v0.0.11
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by jakeharris** [comment]
Sorry about my lack of responsiveness. School et. al. had been catching up with me. 

I'll try and fix this this weekend.

Thanks for reporting all this, by the way. I wish I had made tests of some sort now, haha. Ah well. Maybe that'll be part of my patch work this weekend.

**Comment by rickydazla** [comment]
No worries, I won't nag like your significant other.
