### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by rainmaker666** [javakat/html-significant-other#8]
When I try to install this package I have got this error:

![image](https://cloud.githubusercontent.com/assets/5520135/11030021/7ea57654-86cb-11e5-8e91-4617a1f38f4d.png)

**Comment by o-faro** [comment]
As well.

**Comment by edwinramirez** [comment]
Seems this error is still present. 
Using Atom 1.13.1 x64 on Linux Ubuntu 16.10. ember-cli: 2.10.0. node: 7.4.0

`Installing “html-significant-other@0.5.0” failed.Hide output…

> runas@2.0.0 install /tmp/apm-install-dir-11717-29757-18afdgm/node_modules/html-significant-other/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-11717-29757-18afdgm/node_modules/html-significant-other/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:96: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-11717-29757-18afdgm/node_modules/html-significant-other/node_modules/runas/build'
/tmp/apm-install-dir-11717-29757-18afdgm
└── (empty)


npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
In file included from ../../nan/nan.h:81:0,
                 from ../src/main.cc:1:
../../nan/nan_new.h: In function ‘v8::Local<T> NanIntern::To(v8::Handle<v8::Integer>) [with T = v8::Int32; v8::Handle<v8::Integer> = v8::Local<v8::Integer>]’:
../../nan/nan_new.h:34:64: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
                                                                ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42:0,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:8183:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
In file included from ../../nan/nan.h:81:0,
                 from ../src/main.cc:1:
../../nan/nan_new.h: In function ‘v8::Local<T> NanIntern::To(v8::Handle<v8::Integer>) [with T = v8::Uint32; v8::Handle<v8::Integer> = v8::Local<v8::Integer>]’:
../../nan/nan_new.h:39:65: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
                                                                 ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42:0,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:8177:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::BooleanObject>::return_t NanIntern::Factory<v8::BooleanObject>::New(bool)’:
../../nan/nan_implementation_12_inl.h:49:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:4011:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Script>::return_t NanIntern::Factory<v8::Script>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:166:69: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1319:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Script>::return_t NanIntern::Factory<v8::Script>::New(v8::Local<v8::String>, const v8::ScriptOrigin&)’:
../../nan/nan_implementation_12_inl.h:173:69: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1319:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::String>::return_t NanIntern::Factory<v8::String>::New(const uint8_t*, int)’:
../../nan/nan_implementation_12_inl.h:206:42: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         v8::String::kNormalString, length);
                                          ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:2313:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::String>::return_t NanIntern::Factory<v8::String>::New(v8::String::ExternalStringResource*)’:
../../nan/nan_implementation_12_inl.h:217:66: warning: ‘static v8::Local<v8::String> v8::String::NewExternal(v8::Isolate*, v8::String::ExternalStringResource*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::String::NewExternal(v8::Isolate::GetCurrent(), value);
                                                                  ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:2351:38: note: declared here
                        Local<String> NewExternal(
                                      ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::UnboundScript>::return_t NanIntern::Factory<v8::UnboundScript>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:237:30: warning: ‘static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^~~~~~~~~~~~~~
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1299:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h:237:76: warning: ‘static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1299:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::UnboundScript>::return_t NanIntern::Factory<v8::UnboundScript>::New(v8::Local<v8::String>, const v8::ScriptOrigin&)’:
../../nan/nan_implementation_12_inl.h:244:30: warning: ‘static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^~~~~~~~~~~~~~
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1299:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:81,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h:244:76: warning: ‘static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1299:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/main.cc:1:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:260:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h:255:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘bool NanIdleNotification(int)’:
../../nan/nan.h:288:71: warning: ‘bool v8::Isolate::IdleNotification(int)’ is deprecated: use IdleNotificationDeadline() [-Wdeprecated-declarations]
     return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                                                       ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:6132:22: note: declared here
                 bool IdleNotification(int idle_time_in_ms));
                      ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/main.cc:1:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:472:20: error: variable or field ‘NanAddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:472:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:473:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:478:20: error: variable or field ‘NanRemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:478:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:483:20: error: variable or field ‘NanAddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:483:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:484:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:489:20: error: variable or field ‘NanRemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:489:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^~
../../nan/nan.h:568:15: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template type
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
               ^~~~~~~~~~~~~~~~
../../nan/nan.h:568:31: error: expected ‘,’ or ‘...’ before ‘<’ token
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
                               ^
../../nan/nan.h: In function ‘void _NanWeakCallbackDispatcher(int)’:
../../nan/nan.h:569:42: error: ‘data’ was not declared in this scope
       _NanWeakCallbackInfo<T, P> *info = data.GetParameter();
                                          ^~~~
../../nan/nan.h: At global scope:
../../nan/nan.h:660:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^~~~~~~
../../nan/nan.h:660:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:664:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^~~~~~~~
../../nan/nan.h:664:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:671:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node_buffer.h:56:40: note:   initializing argument 2 of ‘v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((char*)data), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:675:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^~~~
../../nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>, const v8::ScriptOrigin&)’:
../../nan/nan.h:709:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1319:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/main.cc:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>)’:
../../nan/nan.h:716:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:25:0,
                 from /home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/src/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8.h:1319:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/home/edwin/.atom/.node-gyp/.node-gyp/iojs-1.3.13/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-34-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11717-29757-18afdgm/node_modules/html-significant-other/node_modules/runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11717-29757-18afdgm/package.json'
npm WARN apm-install-dir-11717-29757-18afdgm No description
npm WARN apm-install-dir-11717-29757-18afdgm No repository field.
npm WARN apm-install-dir-11717-29757-18afdgm No README data
npm WARN apm-install-dir-11717-29757-18afdgm No license field.
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/edwin/.atom/.apm/.apmrc" "--userconfig" "/home/edwin/.atom/.apmrc" "install" "/tmp/d-11717-29757-15277d9/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11717-29757-18afdgm/npm-debug.log
npm ERR! code 1`
